Modify all the makefile bits for Mac

diff --git a/extra/etc_store b/extra/etc_store
--- a/extra/etc_store
+++ b/extra/etc_store
@@ -1,7 +1,13 @@
 #!/usr/bin/env bash
 
+# Need bash for fancy parameter expansion
+
 for file; do
-    dest_file="${file//%/%%}"
-    dest_file="./etc/${dest_file//\//%s}"
-    cp "$file" "$dest_file"
+    if [ -f "$file" ]; then
+        dest_file="${file//%/%%}"
+        dest_file="./etc/${dest_file//\//%s}"
+        cp "$file" "$dest_file"
+    else
+        >&2 echo "can't copy $file"
+    fi
 done
